add_executable(simdurl_bench bench.c)
target_link_libraries(simdurl_bench PRIVATE simdurl::header_only)
add_executable(simdurl_bench_scalar bench.c)
target_link_libraries(simdurl_bench_scalar PRIVATE simdurl::header_only)
target_compile_definitions(simdurl_bench_scalar PRIVATE SIMDURL_DISABLE_SIMD=1)
foreach(target IN ITEMS simdurl_bench simdurl_bench_scalar)
  set_target_properties(${target} PROPERTIES C_STANDARD 99 C_STANDARD_REQUIRED YES C_EXTENSIONS NO)
endforeach()
